var imagesArray = [

  {"Alexander": "http://i.imgur.com/knS3cfB.jpg"},
  {"Americano": "http://i.imgur.com/BFDw1QK.jpg"},
  {"Angel Face": "http://i.imgur.com/cEwrqUL.jpg"},
  {"Aviation": "http://i.imgur.com/tNwDtDZ.jpg"},
  {"B52": "http://i.imgur.com/NFrcD6z.jpg"},
  {"Bacardi": "http://i.imgur.com/CdLvMA9.jpg"},
  {"Barracuda": "http://i.imgur.com/EQV120r.png"},
  {"Bellini": "http://i.imgur.com/EDrJHvU.jpg"},
  {"Between The Sheets": "http://i.imgur.com/qsjC730.jpg"},
  {"Black Russian": "http://i.imgur.com/PoQNhKm.jpg"},
  {"Bloody Mary": "http://i.imgur.com/Cm7PpMx.jpg"},
  {"Bramble": "http://i.imgur.com/WgfXOpA.jpg"},
  {"Caipirinha": "http://i.imgur.com/ZQgxGND.jpg"},
  {"Casino": "http://i.imgur.com/FohmOuQ.jpg"},
  {"Champagne Cocktail": "http://i.imgur.com/69dScit.jpg"},
  {"Clover Club": "http://i.imgur.com/ByG0zJf.jpg"},
  {"Cosmopolitan": "http://i.imgur.com/2fjofAm.jpg"},
  {"Cuba Libre": "http://i.imgur.com/KFXUtFy.jpg"},
  {"Daiquiri": "http://i.imgur.com/nMGt7GP.jpg"},
  {"Dark 'n' Stormy": "http://i.imgur.com/UTJDER2.jpg"},
  {"Derby": "http://i.imgur.com/YqzMIbQ.png"},
  {"Dirty Martini": "http://i.imgur.com/NXmRCAh.jpg"},
  {"Dry Martini": "http://i.imgur.com/FdOaZmu.jpg"},
  {"Espresso": "http://i.imgur.com/cmRqXsD.jpg"},
  {"French 75": "http://i.imgur.com/Lw677ZX.jpg"},
  {"French Connection": "http://i.imgur.com/ekqtCaF.jpg"},
  {"French Martini": "http://i.imgur.com/U9Td2y4.jpg"},
  {"Gin Fizz": "http://i.imgur.com/q3Wic3d.jpg"},
  {"Godfather": "http://i.imgur.com/gmzR4vU.jpg"},
  {"Godmother": "http://i.imgur.com/zUxtp6X.jpg"},
  {"Golden Dream": "http://i.imgur.com/WYQBk4V.jpg"},
  {"Grasshopper": "http://i.imgur.com/4Xr5iPp.jpg"},
  {"Harvey Wallbanger": "http://i.imgur.com/x4qi29G.jpg"},
  {"Hemingway Special": "http://i.imgur.com/Jn52vcS.jpg"},
  {"Horse's Neck": "http://i.imgur.com/7WoOB42.jpg"},
  {"Irish Coffee": "http://i.imgur.com/Sjvbtau.jpg"},
  {"John Collins": "http://i.imgur.com/5Qg2qiQ.jpg"},
  {"Kamikaze": "http://i.imgur.com/OAC9RlK.jpg"},
  {"Kir": "http://i.imgur.com/5qiw4VT.jpg"},
  {"Lemon Drop": "http://i.imgur.com/NMoVn5L.jpg"},
  {"Long Island Iced Tea": "http://i.imgur.com/ZByE8GX.jpg"},
  {"Mai-Tai": "http://i.imgur.com/kvSJurH.jpg"},
  {"Manhattan": "http://i.imgur.com/tjhHVN3.jpg"},
  {"Margarita": "http://i.imgur.com/aTU0Pay.jpg"},
  {"Mary Pickford": "http://i.imgur.com/DumEnm7.jpg"},
  {"Mimosa": "http://i.imgur.com/rHdJZbs.jpg?1"},
  {"Mint Julep": "http://i.imgur.com/tM9d2hs.jpg"},
  {"Mojito": "http://i.imgur.com/afofRjZ.jpg"},
  {"Monkey Gland": "http://i.imgur.com/0yKWG1y.jpg"},
  {"Moscow Mule": "http://i.imgur.com/EdDPWCr.jpg"},
  {"Negroni": "http://i.imgur.com/yd3v7Qp.jpg"},
  {"Old Fashioned": "http://i.imgur.com/YaWDoPi.jpg"},
  {"Paradise": "http://i.imgur.com/RoWL80V.jpg"},
  {"Pina Colada": "http://i.imgur.com/e5RhqNf.jpg"},
  {"Pisco Sour": "http://i.imgur.com/jGaa97i.jpg"},
  {"Planter's Punch": "http://i.imgur.com/81BXHNh.jpg"},
  {"Porto Flip": "http://i.imgur.com/VarmYfs.jpg"},
  {"Ramos Gin Fizz": "http://i.imgur.com/6o7gA20.jpg"},
  {"Rose": "http://i.imgur.com/NSNv0zX.jpg"},
  {"Russian Spring Punch": "http://i.imgur.com/oCpFnDF.jpg"},
  {"Rusty Nail": "http://i.imgur.com/01QIped.jpg"},
  {"Sazerac": "http://i.imgur.com/WG853ha.jpg"},
  {"Sea Breeze": "http://i.imgur.com/H88BjkR.jpg"},
  {"Sex On The Beach": "http://i.imgur.com/UlWzzvX.jpg"},
  {"Screwdriver": "http://i.imgur.com/k1R1rur.jpg"},
  {"Sidecar": "http://i.imgur.com/w2QhefG.jpg"},
  {"Singapore Sling": "http://i.imgur.com/azHa1td.jpg"},
  {"Spritz Veneziano": "http://i.imgur.com/QCOXm17.jpg"},
  {"Stinger": "http://i.imgur.com/K7nLzU3.jpg"},
  {"Tequila Sunrise": "http://i.imgur.com/pzkvQqm.jpg"},
  {"Tommy's Margarita": "http://i.imgur.com/DoEoEV1.jpg"},
  {"Tuxedo": "http://i.imgur.com/ea9yQEq.jpg"},
  {"Vampiro": "http://i.imgur.com/Wgn2G14.png"},
  {"Vesper": "http://i.imgur.com/mZHqYOe.jpg"},
  {"Whiskey Sour": "http://i.imgur.com/uJTwqVo.jpg"},
  {"White Lady": "http://i.imgur.com/maJ7y5f.jpg"},
  {"Yellow Bird": "http://i.imgur.com/nD9J7Xj.jpg"}
];

module.exports = imagesArray;
